### ISSUE TITLE
Add&update pkgs and files

### ISSUE THREAD

**Issue by DarkPlasma-FF** [Shadeslayer10/PokeRealm#7]
1)Package.json:-

"scripts": {
    "start": "node src",
    "test": "jest src/app.test.js"
}

2)app.test.json:-

const app = require("./app")
const supertest = require("supertest")
const request = supertest(app)

describe("/test endpoint", () => {
    it("should return a response", async () => {
        const response = await request.get("/test")
        expect(response.status).toBe(200)
        expect(response.text).toBe("Hello world");
    })
})

3)In the index.js file, add this code:-

const app = require( "./app");
 const port = process.env.PORT || 3000; 

app.listen(port, () => 
    console.log('Example app listening on port 3000!'), );

4)app.js

const express = require("express");
const app = express();

app.get("/test", (_req, res) =>  {
  res.status(200).send("Hello world")
})
module.exports = app;

**Comment by Shadeslayer10** [comment]
Check src directory
